//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Please enter First name.")]
        [RegularExpression("^([a-zA-Z]+)$", ErrorMessage = "Invalid First Name.")]
        public string Firstname { get; set; }

        [Required(ErrorMessage = "Please enter First name.")]
        [RegularExpression("^([a-zA-Z]+)$", ErrorMessage = "Invalid First Name.")]
        public string Lastname { get; set; }

        [Required(ErrorMessage = "Please enter Your Gender.")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Please enter your Salary.")]
        [Range(1,5000, ErrorMessage = "Salary Must not exceed 5000.")]
        [RegularExpression("^([0-9]+)$", ErrorMessage = "Salary Must Be in Number Formate.")]
        public int salary { get; set; }

        [Required(ErrorMessage = "Please enter Password.")]
      //  [RegularExpression("^(?=.*?[a - z])(?=.*?[0 - 9]).{8,}$", ErrorMessage = "Minimum eight characters, at least one letter and one number.")]
        public string Passwd { get; set; }
    }
}
